config/routes.rb
Rails.application.routes.draw do
  get '/index' => 'index#index'

  root to: "index#index"
  
  devise_for :users

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  resources :bug_forms
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bug_form.rb
class BugForm < ApplicationRecord
  belongs_to :user

  validates :bug_behavior, presence: true
  validates :reproducibility, presence: true
  validates :status, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
end

app/controllers/bug_forms_controller.rb
class BugFormsController < ApplicationController
  before_action :set_bug_form, only: %i[ show edit update destroy ]

  # GET /bug_forms or /bug_forms.json
  def index
    @bug_forms = BugForm.all
  end

  # GET /bug_forms/1 or /bug_forms/1.json
  def show
  end

  # GET /bug_forms/new
  def new
    @bug_form = BugForm.new
    render :new
  end

  # GET /bug_forms/1/edit
  def edit
  end

  # POST /bug_forms or /bug_forms.json
  def create
    @bug_form = BugForm.new(bug_form_params)

    respond_to do |format|
      if @bug_form.save
        format.html { render :index, notice: "Bug successfully added to ticket queue." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bug_forms/1 or /bug_forms/1.json
  def update
    respond_to do |format|
      if @bug_form.update(bug_form_params)
        format.html { redirect_to @bug_form, notice: "Bug form was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bug_forms/1 or /bug_forms/1.json
  def destroy
    @bug_form.destroy
    respond_to do |format|
      format.html { redirect_to bug_forms_url, notice: "Bug form was successfully destroyed." }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bug_form
      @bug_form = BugForm.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def bug_form_params
      params.require(:bug_form).permit(:bug_behavior, :reproducibility, :priority)
    end
end

app/controllers/index_controller.rb
class IndexController < ApplicationController
  def index
    render :index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bug_forms_helper.rb
module BugFormsHelper
end

app/views/bug_forms/_form.html.erb
<%= form_with(model: bug_form) do |form| %>
  <% if bug_form.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(bug_form.errors.count, "error") %> prohibited this bug_form from being saved:</h2>

      <ul>
        <% bug_form.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>



  <div class="actions">
    <%= form_for @bug_form do |f| %>
  <table>
        <tr>
          <td>
            <div class="input-field">
              <select id="bug_form_priority" name="bug_form[priority]">
                <option value="" disabled selected>Choose your option</option>
                <option value="1">Low</option>
                <option value="22">Medium</option>
                <option value="333">High</option>
                <option value="4444">Urgent</option>
              </select>
              <label>Priority</label>
            </div>
          </td>
          
          <%# Urgent => can be only chosen by admin? %>
          <%# Make documentation indicating what is 'Low', 'Medium', etc. %>
        </tr>
        <tr>
          <td><%= f.label :bug_behavior %></td>
          <td><%= f.text_field :bug_behavior %></td>
        </tr>
        <tr>
          <td colspan="2">
            <label for="bug_form_reproducibility">Reproducibility</label>
            <div class="input">
              <textarea id="bug_form_reproducibility" name="bug_form[reproducibility]" class="materialize-textarea"></textarea>
            </div>
          </td>

        </tr>
        <tr>
          <td colspan="2"><%= f.submit "Submit"%></td>
        </tr>
    </table>
  <% end %>
  </div>
<% end %>

app/views/bug_forms/edit.html.erb
<h1>Editing Bug Form</h1>

<%= render 'form', bug_form: @bug_form %>

<%= link_to 'Show', @bug_form %> |
<%= link_to 'Back', bug_forms_path %>

app/views/bug_forms/index.html.erb
<h1>Bug Tracker</h1>

app/views/bug_forms/new.html.erb
<h1>New Bug Form</h1>

<%= render 'form', bug_form: @bug_form %>



<%= link_to 'Back', bug_forms_path %>

app/views/bug_forms/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_bug_form_path(@bug_form) %> |
<%= link_to 'Back', bug_forms_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BugTracker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%# <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-beta/css/materialize.min.css"> %>
  </head>

  <body>
    <header>
      <div class="navbar-fixed">
        <nav>
          <div class="nav-wrapper">
            <div class="container">
              <a href="#" class="brand-logo left">Buggoff!</a>
              <ul class="right">
                <li><%= link_to "Create an Account", new_user_registration_path unless current_user %></li>
                <li><%= link_to "Sign In", new_user_session_path unless current_user %></li>
                <li><%= link_to "Edit Account", edit_user_registration_path if current_user %></li>
                <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete if current_user %></li>
              </ul>
            </div>
          </div>
        </nav>
      </div>
    </header>
    <main>
      <div class="container center">
        <h2><%= flash[:notice] %></h2>
        <h2><%= flash[:error] %></h2>
        <%= yield %>
      </div>
    </main>

    <%# <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script> %>
  </body>
  
</html>